version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-ci-cd
permissions:
  - object: /home/ubuntu/aws-ci-cd/stop_container.sh
    mode: "0755"
  - object: /home/ubuntu/aws-ci-cd/start_container.sh
    mode: "0755"
hooks:
  ApplicationStop:
    - location: stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_container.sh
      timeout: 300
      runas: root
